FROM marcaureln/volta:2.0.2-bookworm-slim AS frontend-builder

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock frontend/.yarnrc.yml ./
COPY frontend/.yarn/ ./.yarn/

RUN yarn install --immutable

COPY frontend/ ./
COPY frontend/.pnp.cjs ./

RUN yarn build



# === Stage: Backend (без cargo-chef, fast build)
FROM rust:1.86-slim AS backend-builder

RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev curl bash musl-tools && \
    rm -rf /var/lib/apt/lists/*

RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /backend
COPY backend/ .

RUN cargo build --release --target x86_64-unknown-linux-musl
RUN strip target/x86_64-unknown-linux-musl/release/rcon-api

# === Final dev image with nginx + backend
FROM nginx:1.27-alpine

RUN apk add --no-cache libssl3 gettext

COPY --from=backend-builder /backend/target/x86_64-unknown-linux-musl/release/rcon-api /usr/local/bin/rcon-api

# ✅ исправлено здесь
COPY --from=frontend-builder /app/dist /var/www/html

COPY nginx/nginx.http.conf /etc/nginx/nginx.http.conf
COPY nginx/nginx.https.conf /etc/nginx/nginx.https.conf

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80
CMD ["/start.sh"]
